[package]
name = "rmanga"
version = "0.0.1"
edition = "2021"


[dependencies]
crossterm = "0.25.0"
isahc = "1.7.2"
serde = { version="1.0.152", features=["derive"] }
serde_json = "1.0.93"
tui = { version="0.19.0", features=["crossterm"], default-features = false }
tui-textarea = "0.2.0"
